# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
app_id: 1E6A8217-5B8A-4B9C-8C7D-9A8B7C6D5E4F
publisher: HoangTrungNguyen
publisher_url: https://github.com/hoangtrungnguyen/esupa_store_pos
display_name: Store Manager
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
# This path is relative to the root directory of your project; The format of icon file must be ico, can not be png or others
# setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en
  - vi


# output: "E:\\Esupa\\esupa-store-deployment\\esupa_installer\\frontend"